name: Release pipeline

on:
  push:
    branches:
      - master
      - feature/danger

jobs:
  archive:
    name: Archive
    env:
      CONFIGURATION: "Release"
      SCHEME: "Actions"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Prepare signing
      env:
        B64_PROV: ${{ secrets.B64_PROV_DIST }}
        B64_CERT: ${{ secrets.B64_CERT_DIST }}
        P12PW: ${{ secrets.P12PW_DIST }}
        KCID: ${{ secrets.KCID }}
        KCPW: ${{ secrets.KCPW }}
      run: |
        ./devops/signing_open.sh $B64_PROV $B64_CERT $P12PW $KCID $KCPW
    - name: Build archive
      run: |
        set -o pipefail && xcodebuild -scheme $SCHEME -sdk iphoneos -configuration $CONFIGURATION archive -archivePath Archive.xcarchive | xcpretty --color --simple
    - name: Close signing
      env:
        KCID: ${{ secrets.KCID }}
      run: |
        ./devops/signing_close.sh $KCID
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: Archive
        path: Archive.xcarchive

  export:
    name: Export ipa
    runs-on: macOS-latest
    needs: archive
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Download archive
      uses: actions/download-artifact@v1
      with:
        name: Archive
    - name: Prepare signing
      env:
        B64_PROV: ${{ secrets.B64_PROV_DIST }}
        B64_CERT: ${{ secrets.B64_CERT_DIST }}
        P12PW: ${{ secrets.P12PW_DIST }}
        KCID: ${{ secrets.KCID }}
        KCPW: ${{ secrets.KCPW }}
      run: |
        ./devops/signing_open.sh $B64_PROV $B64_CERT $P12PW $KCID $KCPW
    - name: Export ipa
      run: |
        set -o pipefail && xcodebuild -exportArchive -archivePath Archive -exportOptionsPlist ./devops/exportOptions.plist -exportPath ./build | xcpretty --color --simple
    - name: Close signing
      env:
        KCID: ${{ secrets.KCID }}
      run: |
        ./devops/signing_close.sh $KCID
    - name: Upload ipa
      uses: actions/upload-artifact@v1
      with:
        name: App
        path: build

