name: Release pipeline

on:
  push:
    branches:
      - master

env:
  AC_ISSUER: "093b7a6a-8833-4791-82d5-3f4ac31c6444"
  AC_PRIVATE_KEY_ID: "RXMK9933VC"
  ARCHIVE_NAME: "Archive"
  ARCHIVE_PATH: "./Archive.xcarchive"
  CONFIGURATION: "Release"
  SCHEME: "Actions"
  TARGET: "Actions"

jobs:
  archive:
    name: Archive
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Prepare signing
      uses: ngeri/prepare-signing@v1.0.0
      with:
        b64_prov: ${{ secrets.B64_PROV_DIST }}
        b64_cert: ${{ secrets.B64_CERT_DIST }}
        p12_pw: ${{ secrets.P12PW_DIST }}
        kc_id: ${{ secrets.KCID }}
        kc_pw: ${{ secrets.KCPW }}
    - name: Build number bump
      uses: ngeri/version-bump@master
      with:
        appstoreConnectPrivateKey: ${{ secrets.AC_PRIVATE_KEY }}
        keyID: "RXMK9933VC"
        issuerID: "093b7a6a-8833-4791-82d5-3f4ac31c6444"
        targetName: "Actions"
    - name: Build archive
      run: |
        set -o pipefail && xcodebuild -scheme $SCHEME -sdk iphoneos -configuration $CONFIGURATION archive -archivePath $ARCHIVE_PATH
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ${{ env.ARCHIVE_PATH }}

  export:
    name: Export ipa
    runs-on: macOS-latest
    needs: archive
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Download archive
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.ARCHIVE_NAME }}
    - name: Prepare signing
      uses: ngeri/prepare-signing@v1.0.0
      with:
        b64_prov: ${{ secrets.B64_PROV_DIST }}
        b64_cert: ${{ secrets.B64_CERT_DIST }}
        p12_pw: ${{ secrets.P12PW_DIST }}
        kc_id: ${{ secrets.KCID }}
        kc_pw: ${{ secrets.KCPW }}
    - name: Export ipa
      run: |
        set -o pipefail && xcodebuild -exportArchive -archivePath $ARCHIVE_NAME -exportOptionsPlist ./devops/exportOptions.plist -exportPath ./build
    - name: Upload ipa
      uses: actions/upload-artifact@v1
      with:
        name: App
        path: build

  upload:
    name: Upload ipa
    runs-on: macOS-latest
    needs: export
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Download ipa
      uses: actions/download-artifact@v1
      with:
        name: App
    - name: Setup App Store Connect authentication
      env:
        AC_PRIVATE_KEY: ${{ secrets.AC_PRIVATE_KEY }}
      run: |
        mkdir -p ./private_keys
        echo "$AC_PRIVATE_KEY" > ./private_keys/AuthKey_$AC_PRIVATE_KEY_ID.p8
    - name: Upload ipa
      uses: actions/upload-artifact@v1
      with:
        name: Key
        path: private_keys
    - name: Validate ipa
      run: |
        set -o pipefail && xcrun altool --validate-app --file $(find . -type f -name "*.ipa") --apiKey $AC_PRIVATE_KEY_ID --apiIssuer $AC_ISSUER | xcpretty --color --simple
    - name: Upload ipa
      run: |
        set -o pipefail && xcrun altool --upload-app --file $(find . -type f -name "*.ipa") --apiKey $AC_PRIVATE_KEY_ID --apiIssuer $AC_ISSUER | xcpretty --color --simple
